#!/usr/bin/env bash

#Cycle the app to refresh

cache=false

while true; do
    read -p $'\e[43;30m--------- Set caching after clear?\e[0m (Y or N) : ' caching

    case $caching in
    [Yy]*)
        cache=true
        break
        ;;
    [Nn]* | *)
        echo "Caching not set"
        break
        ;;
    esac
done
echo "-----init----"
php artisan clear-compiled
php artisan config:clear
echo "config clear"
php artisan route:clear
echo "route clear"
php artisan view:clear
echo "view clear"
php artisan optimize:clear

if [ "$caching" == "true" ]; then
    echo "Caching App"
    php artisan route:cache
    php artisan optimize
    php artisan config:cache
fi

while true; do
    read -p $'\e[43;30m--------- Clear Composer Autoload?\e[0m (Y or N) : ' yn

    case $yn in
    [Yy]*)
        composer dumpautoload --optimize --apcu
        break
        ;;
    [Nn]* | *)
        echo "Composer not changed"
        break
        ;;
    esac
done

exit
